[package]
name = "uniswap"
version = "0.1.0"
authors = ["DaniPopes <danipopes1@proton.me>"]
license = "MIT"
edition = "2021"
readme = "README.md"
documentation = "https://docs.rs/uniswap"
repository = "https://github.com/danipopes/uniswap"
homepage = "https://docs.rs/uniswap"
description = "Simple library for interacting with Uniswap v2 and v3 smart contracts."

[build-dependencies]
ethers-contract = { git = "https://github.com/gakonst/ethers-rs" }

[dependencies]
ethers = { git = "https://github.com/gakonst/ethers-rs" }
thiserror = "1.0"
serde = "1.0"
serde_json = "1.0"

[dev-dependencies]
tokio = { version = "1", features = ["macros"] }
eyre = "0.6"
