[package]
name = "uniswap-rs"
version = "0.1.0"
edition = "2021"

[build-dependencies]
ethers-contract = { git = "https://github.com/gakonst/ethers-rs", features = ["abigen"] }

[dependencies]
ethers = { git = "https://github.com/gakonst/ethers-rs", features = ["abigen"] }
thiserror = "1.0"
serde = "1.0"
serde_json = "1.0"

[dev-dependencies]
tokio = { version = "1", features = ["macros"] }
