[package]
name = "uniswap"
version = "0.1.0"
edition = "2021"
rust-version = "1.62"
authors = ["DaniPopes <danipopes1@proton.me>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/danipopes/uniswap"
homepage = "https://docs.rs/uniswap"
description = "Unofficial Rust SDK library for Uniswap smart contracts."
keywords = ["dex", "uniswap", "sdk", "ethereum", "eth"]

[build-dependencies]
ethers-contract = { git = "https://github.com/gakonst/ethers-rs" }

[dependencies]
ethers = { git = "https://github.com/gakonst/ethers-rs" }
thiserror = "1.0"
serde = "1.0"
serde_json = "1.0"

[dev-dependencies]
tokio = { version = "1", features = ["macros"] }
eyre = "0.6"
