[package]
name = "uniswap-rs"
version = "0.1.0"
edition = "2021"
rust-version = "1.62"
authors = ["DaniPopes <danipopes1@proton.me>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/danipopes/uniswap-rs"
homepage = "https://docs.rs/uniswap-rs"
description = "Unofficial Rust SDK library for Uniswap smart contracts."
keywords = ["dex", "uniswap", "sdk", "ethereum", "eth"]

[build-dependencies]
ethers-contract = { git = "https://github.com/gakonst/ethers-rs" }

[dependencies]
ethers = { git = "https://github.com/gakonst/ethers-rs" }
thiserror = "1.0"
serde = "1.0"
serde_json = "1.0"

[dev-dependencies]
tokio = { version = "1", features = ["macros"] }
eyre = "0.6"

[patch."https://github.com/gakonst/ethers-rs"]
ethers = { git = "https://github.com/danipopes/ethers-rs", branch = "fix/contract-impls" }
ethers-contract = { git = "https://github.com/danipopes/ethers-rs", branch = "fix/contract-impls" }

# ethers = { path = "../ethers-rs" }
# ethers-contract = { path = "../ethers-rs/ethers-contract" }
# ethers-core = { path = "../ethers-rs/ethers-core" }
# ethers-providers = { path = "../ethers-rs/ethers-providers" }
# ethers-signers = { path = "../ethers-rs/ethers-signers" }
# ethers-etherscan = { path = "../ethers-rs/ethers-etherscan" }
# ethers-solc = { path = "../ethers-rs/ethers-solc" }
