use_small_heuristics = "Max"
use_field_init_shorthand = true

# unstable
imports_granularity = "Crate"
wrap_comments = true
comment_width = 100
# TODO: enable on next ethers release
# ignore = ["src/contracts/bindings"]
