name: CI

on:
    push:
        branches: ["master"]
    pull_request:

env:
    ABIGEN_CHECK: true
    RUSTFLAGS: "-D warnings"

jobs:
    test:
        name: test +${{ matrix.toolchain }} @ ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: ["ubuntu-latest", "windows-latest", "macos-latest"]
                toolchain: ["stable", "nightly"]
        steps:
            - uses: actions/checkout@v3
            - uses: dtolnay/rust-toolchain@master
              with:
                  toolchain: ${{ matrix.toolchain }}
                  components: rustfmt
            - uses: Swatinem/rust-cache@v2
              with:
                  cache-on-failure: true
            - name: test
              run: cargo test --all-features

    clippy:
        name: clippy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: dtolnay/rust-toolchain@nightly
              with:
                  components: clippy, rustfmt
            - uses: Swatinem/rust-cache@v2
              with:
                  cache-on-failure: true
            - name: clippy
              run: cargo clippy --tests --all-features

    docs:
        name: docs
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: dtolnay/rust-toolchain@nightly
              with:
                  components: rust-docs, rustfmt
            - uses: Swatinem/rust-cache@v2
              with:
                  cache-on-failure: true
            - name: doc
              run: cargo doc --all-features

    fmt:
        name: fmt
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: dtolnay/rust-toolchain@nightly
              with:
                  components: rustfmt
            - uses: Swatinem/rust-cache@v2
              with:
                  cache-on-failure: true
            - name: fmt --check
              run: cargo fmt --check
