name: CI

on:
    push:
        branches: ["master"]
    pull_request:

env:
    RUSTFLAGS: "-D warnings"

jobs:
    test:
        name: test +${{ matrix.toolchain }} (${{ matrix.job.target }})
        runs-on: ${{ matrix.job.os }}
        strategy:
            fail-fast: false
            matrix:
                job:
                    - os: ubuntu-latest
                      target: x86_64-unknown-linux-gnu
                    - os: ubuntu-latest
                      target: aarch64-unknown-linux-gnu
                    - os: macos-latest
                      target: x86_64-apple-darwin
                    - os: macos-latest
                      target: aarch64-apple-darwin
                    - os: windows-latest
                      target: x86_64-pc-windows-msvc
                toolchain: ["stable", "nightly"]
        steps:
            - uses: actions/checkout@v3
            - uses: dtolnay/rust-toolchain@master
              with:
                  toolchain: ${{ matrix.toolchain }}
                  targets: ${{ matrix.job.target }}
                  components: rustfmt
            - uses: Swatinem/rust-cache@v2
            - name: test
              run: cargo test --all-features

    features:
        name: features
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: dtolnay/rust-toolchain@nightly
            - uses: Swatinem/rust-cache@v2
            - uses: taiki-e/install-action@cargo-hack
            - name: check --feature-powerset
              run:
                  cargo hack check --all --feature-powerset --depth 2 -Z avoid-dev-deps --keep-going

    abigen:
        name: abigen
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: dtolnay/rust-toolchain@nightly
              with:
                  components: rustfmt
            - uses: Swatinem/rust-cache@v2
            - name: build
              env:
                  ABIGEN_CHECK: true
              run: cargo build --tests

    clippy:
        name: clippy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: dtolnay/rust-toolchain@nightly
              with:
                  components: clippy
            - uses: Swatinem/rust-cache@v2
            - name: clippy
              run: cargo clippy --tests --all-features

    docs:
        name: docs
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: dtolnay/rust-toolchain@nightly
              with:
                  components: rust-docs
            - uses: Swatinem/rust-cache@v2
            - name: doc
              run: cargo doc --all-features

    fmt:
        name: fmt
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: dtolnay/rust-toolchain@nightly
              with:
                  components: rustfmt
            - name: fmt --check
              run: cargo fmt --check
