on:
    push:
        branches: ["master"]
    pull_request:

name: CI
env:
    ABIGEN_CHECK: true

jobs:
    test:
        name: test all (${{ matrix.os }} / ${{ matrix.toolchain }})
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: ["ubuntu-latest", "windows-latest", "macos-latest"]
                toolchain: ["stable", "nightly"]
        steps:
            - uses: actions/checkout@v3
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: ${{ matrix.toolchain }}
                  override: true
            - uses: Swatinem/rust-cache@v2
              with:
                  cache-on-failure: true
            - name: test --all
              run: cargo test --all --all-features

    clippy:
        name: clippy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  components: clippy, rustfmt
                  profile: minimal
                  toolchain: nightly
                  override: true
            - uses: Swatinem/rust-cache@v2
              with:
                  cache-on-failure: true
            - name: clippy --all
              run: cargo clippy --all --tests --all-features

    docs:
        name: docs
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  components: rust-docs, rustfmt
                  profile: minimal
                  toolchain: nightly
                  override: true
            - uses: Swatinem/rust-cache@v2
              with:
                  cache-on-failure: true
            - name: doc --all
              run: cargo doc --all --all-features

    fmt:
        name: fmt
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  components: rustfmt
                  profile: minimal
                  toolchain: nightly
                  override: true
            - uses: Swatinem/rust-cache@v2
              with:
                  cache-on-failure: true
            - name: cargo fmt --check
              run: cargo fmt --check
