on:
    push:
        branches: ["master"]
    pull_request:

name: CI

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
            - uses: Swatinem/rust-cache@v1
            - name: "cargo test --all"
              run: cargo test --all --all-features

    clippy:
        name: clippy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
                  override: true
                  components: clippy
            - uses: Swatinem/rust-cache@v1
            # Run clippy
            - name: "clippy --all"
              run: cargo clippy --all --tests --all-features

    fmt:
        name: fmt
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
                  override: true
                  components: rustfmt
            - uses: Swatinem/rust-cache@v1
            # Check fmt
            - name: "rustfmt --check"
              run: rustfmt --check
